# Data Analytics II

                                                     -By Aditya Nikam(TE AI & DS)

1.Implement logistic regression using Python/R to perform classification on
Social_Network_Ads.csv dataset.

2.Compute Confusion matrix to find TP, FP, TN, FN, Accuracy, Error rate,
Precision, Recall on the given dataset.

In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')#we use this to ignore the warnings means in the output warnings should not appear

C:\Users\champ\PycharmProjects\Tutorials\a\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.8.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\champ\PycharmProjects\Tutorials\a\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
df=pd.read_csv(r"C:\Users\champ\Downloads\Social_Network_Ads.csv")#this is to import the dataset.
#The dataset is a csv file.df is the name given to the dataset
df#this is written to display the dataset

      User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [3]:
df.head()#it display the first five rows of the dataset.Its default value is 5

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510    Male  19.0          19000.0          0
1  15810944    Male  35.0          20000.0          0
2  15668575  Female  26.0          43000.0          0
3  15603246  Female  27.0          57000.0          0
4  15804002    Male  19.0          76000.0          0

In [4]:
df.shape#it tells the number of rows and columns in the dataset so here are 400 rows and 5 columns

(400, 5)

In [5]:
df.isnull().sum()#This displays the number of null values in each column

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
df.info()#It gives the summary of the dataframe and it tells how many non null values are there in each column ,what 
#is the data type of each coloumn,how many columns are there in the dataset
#Here we cans ee that in our dataset there are 5 coloumns where 2 coloumns have int Datatype
#2 coloumns have float data type and 1 column has object data type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   User ID          400 non-null    int64
 1   Gender           400 non-null    object
 2   Age              400 non-null    float64
 3   EstimatedSalary  400 non-null    float64
 4   Purchased        400 non-null    int64
dtypes: float64(2), int64(2), object(1)
memory usage: 15.8+ KB

In [7]:
df['Purchased'].unique()# it tells that there are two types of values only in Purchased column which are 0 and 1
#1 means purchased and 0 means not purchased

array([0, 1], dtype=int64)

In [8]:
#Lets convert Gender column values into numerical
df["Gender"]=df["Gender"].replace({"Female":0,"Male":1})#Now 1 represents male and 0 represents female
df.head()
#We converted the Gender column values to 1 and 0 because we are going to apply Logistic Regression and all machine 
#learning algorithms only understand numeric data and not categorical so we converted the values
#Now all data in dataset is numeric now we can appy Logistic Regression

    User ID  Gender   Age  EstimatedSalary  Purchased
0  15624510       1  19.0          19000.0          0
1  15810944       1  35.0          20000.0          0
2  15668575       0  26.0          43000.0          0
3  15603246       0  27.0          57000.0          0
4  15804002       1  19.0          76000.0          0

In [9]:
x=df[["User ID","Gender","Age","EstimatedSalary"]]#Input to our model
y=df["Purchased"]#this is the output of our model

In [10]:
from sklearn.model_selection import train_test_split#Here we are importing train_test_split from sci-kit learn
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2, random_state=42)#We are dividing the values of the User
#ID,Gender,Age and Estimated Salary which are inputs(X) for the model and Purchased which is output for the model(Y)
#So we are dividing their values into training and testing 80% of data is training
#test_size=0.2 denotes 20% of data wil be testing dataset
#random state ensures that whenever we run the program every time the same values of the data are taken for training 
#and testing means suppose we have 100 records in our data out of which we are using 80  for training and 20 for testing
#so every time the same 80 values will be in training and same 20 values will be in testing means not a single record of 
#training data will go in the testing data and not single value of testing data will come in training data means there will
#be no shuffling of records the same data will be used for training and testing every time we run the program this is 
#the use of random state

#In random_state=42 42 is just a normal number there is no role of zero we have to just write it when we are using 
#random_state  we can use any other number other than zero as well like 1,4,10 etc.42 is the most common number you see
#in programs

In [11]:
from sklearn.linear_model import LogisticRegression#we are importing Logistic regression from sci-kit learn
model = LogisticRegression()#we created object of Logistic Regression

#Logistic Regression is used for classification problems.In Linear regression we predicted numerical value but 
#Logistic Regression is used to predict categorial value like whether the email is spam or not(binary classification as 
#only two values “spam” or “not spam”),Positive or Negative,Pass or Fail,Yes or No,True or False,will the customer buy 
#insurance or not etc.In Logistic Regression the Sigmoid Function converts the Input variable(X) between 0 and 1.
#The formula of Sigmoid function is  y=1/1+e^-x here y is dependent variable(what we want to predict) and x is Independent
#variable and  the graph is of S shape.

In [12]:
model.fit(xtrain, ytrain)#it teaches the Linear regression model using the training dataset means here we have the inputs
#in xtrain and we have outputs also already defit for the inputs in ytrain now the model learns this data so that it 
#can predict values when any unseen/new data comes to predict

LogisticRegression()

In [13]:
y_pred = model.predict(xtest)#it tells the model to predict the output for the input(xtest).We are testing the model here
#after training

In [14]:
from sklearn.metrics import accuracy_score #sklearn.metric is used to import metrics
score=accuracy_score(ytest,y_pred)#Accuracy score formula is number of correct predictions/total no.of predictions
#ytest means the correct outputs and y_predicted means predicted outputs
score#We see that our accuracy is 0.7375 means 73.75% so it is not very good nor very bad
#To

0.7375

In [15]:
#Confusion Matrix is a table that helps you to know how well the model is performing.It divides the predictions in four 
#types which are True Positive(TP),True Negative(TN),False Positive(FP) & False Negative(FN)

#True Positive(TP)means when model predicted answers match to the actual output
#Like for Example if a model predicts that student will pass the exam and if the student really passes the exam then its 
#True Positive

##True Negative(TN)also means when model predicted answers match to the actual output
#Like for Example if a model predicts that student will fail the exam and if the student fails(actual output) the exam 
#then its True Negative

#False Positive(FP) and False Negative(FN) means when the model predicted answers match to the actual output

#Like for Example if a model predicts that student will fail the exam and if the student pass(actual output) the exam 
#then its False Negative(FN)

#If a model predicts that student will pass the exam and if the student fails(actual output) the exam 
#then its False Positive

In [16]:
from sklearn.metrics import confusion_matrix
print("Confusion Matrix:\n", confusion_matrix(ytest, y_pred))#it creates a confusion matrix of model's predicted answers
#(y_pred)and actual answers(ytest)

Confusion Matrix:
 [[49  3]
 [18 10]]

In [18]:
TP,FP,FN,TN=confusion_matrix(ytest, y_pred,labels=[0,1]).reshape(-1)#labels=[0,1]tells the confusion matrix that we have 
#two outputs which is either 0(fail) or 1(pass) so 0 is our negative class and 1 is our positive class
#TP,FP,TN,FN=confusion_matrix(ytest, y_pred) creates a matrix of confusion matrix and we convert that matrix into list
#using reshape(-1) so we easily access individual elements like TP,FN,FP and TN

In [23]:
print("TP =",TP)#printing value of TP
print("FP =",FP)#printing value of FP
print("FN =",TN)#printing value of FN
print("TN =",FN)#printing value of TN

TP = 49
FP = 3
FN = 18
TN = 10

In [20]:
accuracy=(TP+TN)/(TP+FP+TN+FN)#formula to calculate accuracy
precision=TP/(TP+FP)#formula to calculate precision
recall=TP/(TP+FN)#formula to calculate recall
f1_Score=(2*precision*recall)/(precision+recall)#formula to calculate f1 score

In [21]:
print("Accuracy = ",accuracy)#printing accuracy
print("Precision = ",precision)#printing precision
print("Recall = ",recall)#printing recall
print("F1 Score = ",f1_Score)#printing f1 score

Accuracy =  0.8375
Precision =  0.9423076923076923
Recall =  0.8305084745762712
F1 Score =  0.8828828828828829